name: Java CI with Maven

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Codeball
        uses: sturdy-dev/codeball-action@v2
        with:
            # For all configuration options see https://github.com/sturdy-dev/codeball-action/blob/v2/action.yml
            approvePullRequests: "true"
            labelPullRequestsWhenApproved: "true"
            labelPullRequestsWhenReviewNeeded: "false"
            failJobsWhenReviewNeeded: "false"
