name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
        working-directory: tecttitans-app
      - name: Build
        run: npm run build
        working-directory: tecttitans-app
      - name: Test
        run: npm run test
        working-directory: tecttitans-app
      - name: Lint
        run: npm run lint
        working-directory: tecttitans-app
      - name: Deploy
        uses: nwtgck/actions-netlify@v1.4.1
        with:
          publish-dir: './tecttitans-app/build'
          production-branch: 'master'
          github-token: ${{ secrets.GITHUB_TOKEN }}
